### PR TITLE
Search

### PR DESCRIPTION
**Pull request by marizoldi**
Initial Django implementation of Ajax Search query

### CODE REVIEW

**Review by leunga1000 — COMMENTED** [review]
Seems pretty cool - does it need a @login_required?

**Comment by marizoldi** [comment]
No because it is on the landing page, so it is for everyone. But there is also a search form when you log in. Should I treat this differently?

**Comment by leungant** [comment]
Depends whether you want to allow people/web spiders that haven't signed up to find users etc... if you wanted separate behaviour but with one search url one could just check to see if request.user was populated or None and change the search query appropriately? Either way, in terms of what's been implemented looks fine to merge.

**Comment by marizoldi** [comment]
I will try this as second iteration

**Pull request merged**
