### PR TITLE
Sending and receiving messages API

### PR DESCRIPTION
**Pull request by gerygeo**
API to create and send messages and extract a list of conversations between users.
To send messages use the link:
http://127.0.0.1:8000/api/sendmessage/?recipient=USERNAME&sender=USERNAME&subject=''&body=SOMETEXT
Then to check whether the message was receive login as the recipient and view the messages

To view a json list of the messages between two users use the following link:
http://127.0.0.1:8000/api/messages/?recipient=USERNAME&sender=USERNAME
A json list should display if there are any messages between the users.

### CODE REVIEW

**Comment by marizoldi** [comment]
Hi @gerygeo 
I am logged in as a user. If I click on the first link I get this:
screen shot 2016-12-21 at 20 24 47

**Comment by gerygeo** [comment]
Hi @marizoldi ,

Sorry should have explained it better:

When using the link:
http://127.0.0.1:8000/api/sendmessage/?recipient=USERNAME&sender=USERNAME&subject=''&body=SOMETEXT

you need to put some username (the recipient) as USERNAME then another username (sender) for the second USERNAME and then SOMETEXT  should be the message you want to sent; this needs to be in quotes.

For the second link:
http://127.0.0.1:8000/api/messages/?recipient=USERNAME&sender=USERNAME
You only need ttwo different usernames intead of USERNAME.

Can you try this?

**Comment by marizoldi** [comment]
The issue is that once I click on the first link I get this error message. Do I have to install some requirements or migrate the db?

**Comment by gerygeo** [comment]
No, only need to replace the USERNAMEs with valid usernames and the SOMETEXT with the actual message in quotes.

I will have a look of how to handle this in a better way when the username is not valid.

**Comment by marizoldi** [comment]
Ah ok sorry now I understood. Ok it works now

**Pull request merged**
