### PR TITLE
initial commit for sticky element

### PR DESCRIPTION
**Pull request by yanabar**
needs more work!

### CODE REVIEW

**Comment by marizoldi** [comment]
Hi @yanabar can you also add what I should be seeing. Right now the landing page is this (firefox):
screen shot 2016-12-12 at 22 47 33
and if I scroll down I see this:

screen shot 2016-12-12 at 22 47 43

**Comment by yanabar** [comment]
@marizoldi my FF view - will be pushing new code soon I hope:
image

**Comment by yanabar** [comment]
@marizoldi I need to investigate a bit more on this: but it should look like this:
image

**Comment by marizoldi** [comment]
Ok it looks like the one you posted now. and when I click on e.g. Map:
screen shot 2016-12-14 at 15 07 22

If that is the intented I can merge it.

**Comment by yanabar** [comment]
@marizoldi - yes please merge this for now 👍

**Pull request merged**
