### PR TITLE
Erehwon messages app

### PR DESCRIPTION
**Pull request by gerygeo**
Can you please test the changes to the page displaying the messages? Thanks

### CODE REVIEW

**Comment by marizoldi** [comment]
Sign in etc removed, the frame is larger now. The same thing with the Notifications (double link) happens also on Write message. Can you remove this too? Another thing I noticed, once you click on a received message, the notification 'You have 1 new message' does not disappear. Steps to reproduce: Send a message to yourself, click on the received message to read it, hit back. The You have a new message is there.

**Comment by gerygeo** [comment]
Removed the double link from Messages; reverted the frame size.

Agree about the notification 'You have 1 new message' - it only disappears when you refresh the screen.

Should I add the two changes and then can look into notification separately?

**Comment by marizoldi** [comment]
Frame size was good. Yes if you update this PR I can merge it and you can look the 'You have x new messages' issue separately.

**Comment by gerygeo** [comment]
OK, Should I leave the frame as it currently is? And then only remove the double link

**Comment by marizoldi** [comment]
yes, just leave it as is for now.

**Pull request merged**
